---
title: "Opportunities"
---

<style type="text/css">
body{ /* Normal  */
      font-size: 16px;
  }
}
</style>

We are currently recruiting two Ph.D. positions associated with ICEBERG. Descriptions of each position are below. Additional PhD, post-doc and research programming positions are also being recruited for ICEBERG; prospective students, post-docs, and research programmers with an interest in combining satellite imagery and high performance computing should contact ICEBERG PI Heather Lynch (heather.lynch@stonybrook.edu) for more information.

**Northern Arizona University**

Dr. Mark Salvatore is seeking applications for a PhD student to start in the Fall of 2018.  The student will work with high-resolution multispectral satellite data to identify, characterize, and map geologic units throughout the ice-free regions of Antarctica.  As part of a large collaborative and federally funded project, the student will also work closely with researchers, computer programmers, and students at collaborating institutions.  A successful candidate will have a strong background in surface geology, remote sensing, geographic information systems, and/or geologic mapping.  Prior research experience and computer programming skills are preferred.
The student will become a member of the dynamic and evolving Department of Physics & Astronomy at Northern Arizona University.  With a growing emphasis on planetary sciences, students in this program develop a deep understanding of planetary formation and evolution, remote sensing, spectroscopy, and planetary surface processes.  PhD students benefit from a full tuition waiver, a competitive stipend, and have the opportunity to participate in the campus healthcare plan.  Northern Arizona University is located in beautiful Flagstaff, Arizona, a four-season town located at the base of the San Francisco peaks and 70 miles from the Grand Canyon.  The Department of Physics & Astronomy is home to a friendly, engaging, and welcoming environment for individuals of all races, ethnicities, sexual orientations, and world views.
Applications are due by December 15, 2017.  Interested students should contact Dr. Salvatore directly (mark.salvatore@nau.edu) prior to submitting an application.

**University of California, Santa Barbara**

The Cryo-Hydrologic Remote Sensing Lab in the Department of Geography at the University of California - Santa Barbara is seeking prospective PhD students to start in 2018. The funded project aims to understand water balance in Arctic glacial systems through integration of DEMs and imagery-enabled classification of hydrological features.
Candidates with a background in remote sensing, GIS, or earth science, and strong programming skills (e.g. in IDL, Python, Matlab) are encouraged to apply.

Applicants should contact Prof. Vena Chu (venachu@ucsb.edu) with a CV/resume and a statement of research interests. For more information about the Graduate Program in Geography at UCSB, see the Geography Graduate Program Description (application deadline is December 15th).
